version: '3.8'
services:
  my.bot:
    build: .
    volumes:
      - './:/usr/src/app/'
    depends_on:
      - db
  db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: "db_bot"
      POSTGRES_USER: "telegramBot"
      POSTGRES_PASSWORD: "telegramBot123"
    ports:
      - "5432:5432"